version: "3.9"
services:
  hello-world:
    build: .
    image: hello-world
    container_name: hello-world
    networks:
     - hello-world_network
    ports:
     - "8080:8080"
     - "9464:9464"
    depends_on:
      - world-countries
  world-countries:
    build: ./world-countries
    image: world-countries
    container_name: world-countries
    networks:
     - hello-world_network
    ports:
     - "3000:3000"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
     - hello-world_network
    ports:
     - "9411:9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - "./metrics/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
     - hello-world_network
    ports:
     - "9090:9090"
  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
     - hello-world_network
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
     - "4318:4318" # HTTP
     - "4317:4317" # gRPC
    depends_on:
      - apm-server
  apm-server:
    image: elastic/apm-server:7.17.3
    container_name: apm-server
    networks:
     - hello-world_network
    ports:
     - "8200:8200"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
     - hello-world_network
    ports:
     - "5601:5601"
    depends_on:
      - elasticsearch
      - apm-server
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
     - hello-world_network
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
      - hello-world_esdata1:/usr/share/elasticsearch/data:rw
networks:
  hello-world_network:
    name: hello-world_network
    driver: bridge
volumes:
  hello-world_esdata1:
    name: hello-world_esdata1
    driver: local
