version: "3.9"
services:
  hello-world:
    image: hello-world
    container_name: hello-world
    networks:
     - hello-world_network
    ports:
     - "8080:8080"
     - "9464:9464"
    depends_on:
      - world-countries
  world-countries:
    image: world-countries
    container_name: world-countries
    networks:
     - hello-world_network
    ports:
     - "3000:3000"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
     - hello-world_network
    ports:
     - "9411:9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - "./metrics/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
     - hello-world_network
    ports:
     - "9090:9090"
  apm-server:
    image: elastic/apm-server:7.17.3
    container_name: apm-server
    environment:
      - logging.level=debug
    networks:
     - hello-world_network
    ports:
     - "8200:8200"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
     - hello-world_network
    ports:
     - "5601:5601"
    depends_on:
      - elasticsearch
      - apm-server
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
     - hello-world_network
    ports:
     - "9200:9200"
     - "9300:9300"
networks:
  hello-world_network:
    name: hello-world_network
    driver: bridge